import openai
import sys 

#Enter API_KEY
openai.api_key = ""

# Returns the response generated by OpenAI's ChatCompletion model
def chat(prompt):
    response = openai.ChatCompletion.create(
        model = "gpt-4o-mini",
        messages = [{"role": "user", "content": prompt}]
    )
    return response.choices[0].message.content.strip()

if __name__ == "__main__":
    # Utilises the arguments from the system input stream to create a prompt
    prompt = "".join(sys.argv[1:])
    response = chat(prompt)
    # Outputs the response to the standard output stream
    print(response)
    
